# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c7ba2585-adfa-4320-a0f5-4af37d7c4bba";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/558931ca-0365-4663-a0f6-07ae8f77f84b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
